project:
  type: website
  output-dir: _site

website:
  title: "Polars Eval Metrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting_started.qmd
        text: Getting Started
      - href: metric.qmd
        text: Metric

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3

execute:
  freeze: auto