project:
  type: website
  output-dir: _site
  resources:
    - coverage

website:
  title: "Polars Eval Metrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quickstart.qmd
        text: Quick Start
      - text: Examples
        menu:
          - href: metric_dfine.qmd
            text: MetricDefine
          - href: metric_evaluator.qmd
            text: MetricEvaluator
      - href: coverage/index.html
        text: Coverage
    right:
      - icon: github
        href: https://github.com/elong0527/demo_eval_metric
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    code-copy: true
    code-overflow: wrap
    css: styles.css

execute:
  freeze: auto