project:
  type: website
  output-dir: _site

website:
  title: "Polars Eval Metrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting_started.qmd
        text: Getting Started
      - text: Examples
        menu:
          - href: metric.qmd
            text: MetricDefine
      - href: coverage.qmd
        text: Coverage
    right:
      - icon: github
        href: https://github.com/elong0527/demo_eval_metric
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    code-copy: true
    code-overflow: wrap
    css: styles.css

execute:
  freeze: auto